### ISSUE TITLE
Curly braces

### ISSUE THREAD

**Issue by SteveHindmarsh** [mmajcica/DeploySsrs#10]
1. I'm finding the documentation is not explaining exactly how the DB place holders  {{Server}}\{{Instance}} in the configuration file are used? I understand your code is creating the Datasource from the parameters used here but how do I feed in the variables for  {{Server}}\{{Instance}}? I'm currently just putting the actual connection strings into the xml file. Doing it this way I am expecting to create a totally separate xml file for each solution configured environment? I'm sure that's not what you're intending? 
The Visual Studio Reporting project (Microsoft Reporting Services Projects) I'm using does not allow us to have different connection strings in the datasource for each project configuration item (Debug, Release etc), so I don't understand where you're even expecting to pick up an environment specific value for those placeholders?
2. The xml file example you give has no examples of syntax for the datasets but I seem to have guessed that by using <DataSets><DataSet> is this correct? 
3. Can you please explain how the security inheritance is working? The existing inheritance seems to be forgotten if I place a single extra security on a folder where I have not also included the parent securities? Are there any element attributes (e.g. includeInheritance) we can use here which you perhaps haven't explained? (perhaps changing the <security> collection node name to<securities> will help it's intelligibility too.
4. Thanks very much for a marvellous TFS Extension otherwise, its very much appreciated, hope you can answer these questions?

**Comment by mmajcica** [comment]
Hi Steve,

let me try to answer some of your questions:

1. Placeholders li {{Server}}{{Instance}} are set by a different task in your build/release. I usually use the Replace tokens task (https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens).
This values now can be set in your release definition as variables and have a different value for each of the environments you defined for your release. Check the following post, it is talking about the SSIS task but these things are quite similar, http://blog.majcica.com/2018/04/25/deploy-ssis-packages-from-tfs-vsts-build-release/.
2. Datasets are supporte and you can find some examples here on Github in between closed issues.
3. Security works in the exact way as it does in SSRS. If you set a certain priviledges on a folder, only that item in SSRS will get those set, I do not take care of inheritance or similar.
4. Yaw. I'm hoping to find some time to document it better in the near future.
