### ISSUE TITLE
Groups and Roles are not added to the security during deployment

### ISSUE THREAD

**Issue by sqlkabauter** [mmajcica/DeploySsrs#11]
The roles I added to the security inside my XML configuration are not added to SSRS during deployment.

I used the following XML as example:

```
<?xml version="1.0" encoding="utf-8"?>
<Folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" Name="Root">
  <Folders>
    <Folder Name="MyFolder">
      <Reports>
        ...
      </Reports>
      <Security Name="myuser2">
        <Roles>
          <Role>Browser</Role>
          <Role>Content Manager</Role>
        </Roles>
      </Security>
    </Folder>
  </Folders>
  <Security>
    <Security Name="myuser1">
      <Roles>
        <Role>Browser</Role>
        <Role>Content Manager</Role>
      </Roles>
    </Security>
  </Security>
</Folder>
```
When testing the PowerShell functions I see that the `Set-SecurityPolicy()` function returns the folder path `/Root `for the root folder and `/MyFolder/MyFolder ` for the MyFolder folder.

It seems that the folder name is added to one to many times to the path.

**Comment by mmajcica** [comment]
Thank you. I'll publish a new version of extension tomorrow.

**Comment by mmajcica** [comment]
A new version with your changes is published. Sorry for the delay.
