### ISSUE TITLE
Question: Does this support SSRS 2017?

### ISSUE THREAD

**Issue by Swellenator** [mmajcica/DeploySsrs#13]
Hi,

Does this support SSRS 2017? My understanding is SSRS 2017 uses a new REST API rather than the old web service. 

Or does using PowerShell mean you don't need to worry about the web service?

Thanks

**Comment by mheptinstall** [comment]
The ReportService2010 web service is still available in SSRS 2017 so this will still work

**Comment by acds** [comment]
any confirmation for 2017 support wooed be good?

**Comment by mmajcica** [comment]
@acds as mentioned above, any version of SSRS that exposes ReportService2010 web service will remain compatible with this extension as the implementation is based on it.
