### ISSUE TITLE
Special characters show up wrong in the deployed

### ISSUE THREAD

**Issue by Sjors-Boom** [mmajcica/DeploySsrs#15]
When we deploy a repport with special characters such as ě, ř and č.
They show up wrong in de deployed report.
When we download the repports they look like this "Ä"

**Comment by Sjors-Boom** [comment]
I tracked it down to the following command:
```powershell
[xml]$Definition = Get-Content -Path $RdlPath
```
Changed it to:
```powershell
[xml]$Definition = Get-Content -Encoding UTF8 -Path $RdlPath
```
Now it works like a charm.

**Comment by mmajcica** [comment]
Solved in https://github.com/mmajcica/DeploySsrs/pull/16
