### ISSUE TITLE
SSRS Deploy - Configuration File provided is not valid

### ISSUE THREAD

**Issue by Petapacket** [mmajcica/DeploySsrs#22]
Hi,

I do not understand what file i should point the SSRS configuration file parameter to, please advise as i cannot find a resource on this but want to use the component.

The error:
_2019-01-28T11:06:22.2915936Z ##[error]Provided configuration file path D:\Program Files\Microsoft SQL Server\MSRS13.MSSQLSERVER\Reporting Services\ReportServer\ is not valid._

I have tried pointing to rsreportserver:
![image](https://user-images.githubusercontent.com/47110445/51839914-7f0d5e00-2302-11e9-830b-9522416f2f0f.png)

The error:
2019-01-28T13:52:42.5160773Z ##[error]Invalid configuration file type.

Assistance would be appreciated. :)

**Comment by mmajcica** [comment]
It is about the configuration file that you should write and keep in your source control (or as a part of your artifact), that again is available during the build/release.
Here is an example of the config file https://github.com/mmajcica/DeploySsrs/blob/master/examples/ReportConfiguration.xml
It will allow you to create folders and place your reports in them but also will allow you to manage the security.
