### ISSUE TITLE
The 'class' keyword is not supported in this version of the language.

### ISSUE THREAD

**Issue by batespe** [mmajcica/DeploySsrs#30]
When I try and use this tool I get the error below:-

2019-05-10T11:17:37.1366854Z ##[section]Starting: Deploy reports
2019-05-10T11:17:37.1572959Z ==============================================================================
2019-05-10T11:17:37.1573131Z Task         : Deploy MS SQL SSRS Reports
2019-05-10T11:17:37.1573274Z Description  : Deploy items on MS SQL SSRS server based on a configuration file.
2019-05-10T11:17:37.1573385Z Version      : 3.1.4
2019-05-10T11:17:37.1573479Z Author       : Mario Majcica
2019-05-10T11:17:37.1573590Z Help         : 
2019-05-10T11:17:37.1573692Z ==============================================================================
2019-05-10T11:17:38.6149542Z ##[error]At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1135 char:1
+ class Folder
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1165 char:13
+     [string]Path()
+             ~~~~
Unexpected token 'Path' in expression or statement.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1165 char:18
+     [string]Path()
+                  ~
An expression was expected after '('.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1176 char:1
+ class Report
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1201 char:1
+ class DataSet
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1226 char:1
+ class DataSource
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1268 char:1
+ class RoleAssignment
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1279 char:14
+     [string] ToString() { return "$($this.Name)" }
+              ~~~~~~~~
Unexpected token 'ToString' in expression or statement.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1279 char:23
+     [string] ToString() { return "$($this.Name)" }
+                       ~
An expression was expected after '('.

At D:\TFS2018Agent\Marg\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.4\ps_modules\ssrs.psm1:1282 char:1
+ class SsrsDataSource
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

Not all parse errors were reported.  Correct the reported errors and try again.

**Comment by batespe** [comment]
I just figured this out. My build server is Windows 2012 Server and have downloaded update for powershell - https://www.microsoft.com/en-us/download/details.aspx?id=54616

Now everything is working well.

**Comment by RobinCpl** [comment]
Is it possible to specify the path to pwsh.exe for the DeploySSRS extension? For some reasons, the default PoweShell version on the server is 4.0. There is also v7.2 but the extension obviously does not see it.
