### ISSUE TITLE
Security not applied at report level

### ISSUE THREAD

**Issue by bajmming** [mmajcica/DeploySsrs#32]
Hi,

The DeploySsrs is working well for us and we have our first CD pipeline setup for reports, but I've noticed that security at the report level is not applied.  I can apply security at Folder level, but not for individual reports.

In the script it passes in _Folder_ and _Name_ as params to _Set-SecurityPolicy_, but only Folder is used.

Is this a bug or not supported?  I'm happy to submit a PR.

I've attached an example config below...
```
{
  "Name": "Root",
  "Folders": [
    {
      "Name": "Some general reports",
      "Hidden": false,
      "Reports": [
        {
          "Name": "My report",
          "Hidden": false,
          "FileName": "My Report.rdl",
          "Security": [
            {
              "Name": "mydomain\\someusers",
              "Roles": [
                "Browser"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Cheers,

Ben

**Comment by mmajcica** [comment]
If security is not applied on the report level, it should be a bug.
Considering the following line, https://github.com/mmajcica/DeploySsrs/blob/66777e1d4ff42af10e9f224c74557d82491fecdc/task/ps_modules/ssrs.psm1#L391
I suppose it should be responsible for applying securiti settings over the report. 
I'm looking at this from my cell phone, thus I may be wrong.
If you can test it, and in case make a PR, I'll be more than happy to accept it and publish a new version.

**Comment by bajmming** [comment]
Sounds good and I'll create a PR soon.  I also want to be able to set the Description property for Data Sources, Data Sets and Folders so I'll create a separate PR for that.

**Comment by bajmming** [comment]
PR submitted.  

If you add security at the report level and subsequently remove the permissions then the permissions will not be removed during deployment unless the _InheritParentSecurity_ flag is set to true.  

I wasn't sure whether there should be an Else in the code below to automatically apply Parent level security if there are no Roles, but this might cause issues for existing deployments...so seemed better for someone to set _InheritParentSecurity_  explicitly.

For example we could do this?
```
                if ($RoleAssignments)
                {
                    ...
                }
                else 
                {
                    if(-not (Test-InheritParentSecurity $Proxy $Path))
                    {
                       Set-InheritParentSecurity $Proxy $Path
                    }
                }
```

**Comment by mmajcica** [comment]
@bajmming a new version is published.

**Comment by bajmming** [comment]
Hi Mario, that's great...thanks for publishing so quickly :)
