### ISSUE TITLE
Report Files Path with wildcard

### ISSUE THREAD

**Issue by weetouches** [mmajcica/DeploySsrs#34]
Hello

I'm trying to use **/*.rdl in the report files path but I Always have this Following error message

Provided files folder path C:\TFS\Agents\SSI\SSRS\ssrs-dev-cd1\_work\r1\a\**\*.rdl is not valid.

All my rdl file are located in several folders under this folder C:\TFS\Agents\SSI\SSRS\ssrs-dev-cd1\_work\r1\a\SSRS\SSRS\MyFolder\

Is it the correct that i m using wildcard in report files path

Tks

**Comment by eshwarboini** [comment]
@weetouches  Did you find any solution to the issue you have raised? I'm stuck at the same issue and couldn't understand what's wrong with the path. Do we have to provide path in some special pattern?

**Comment by eshwarboini** [comment]
@weetouches ..  You have to enter the folder path rather than file path. That should resolve your issue

**Comment by osatchel15** [comment]
I have the same problem. I tried hitting different directories, wrapping the path in quotes, etc. to no avail.

**Comment by mmajcica** [comment]
All of the reports do need to be listed, there is no support for ** over rdl files.
