### ISSUE TITLE
how to pass server name into configuration file

### ISSUE THREAD

**Issue by LuisCoelho1971** [mmajcica/DeploySsrs#38]
We have create the configuration file using the var {{Server}} in the data source configuration, 
the result of the deploy doesn't appear modified:

This is the information of the config file:
![image](https://user-images.githubusercontent.com/58854654/70808692-23cc4900-1db8-11ea-95e8-ac48308028ac.png)

In the release pipeline the variables are created:
![image](https://user-images.githubusercontent.com/58854654/70808659-0dbe8880-1db8-11ea-9b43-2ebc9e7b7d8d.png)

And the task as the following info:
![image](https://user-images.githubusercontent.com/58854654/70808894-92a9a200-1db8-11ea-8a4e-062b408102bf.png)

thank you.

**Comment by dhabierre** [comment]
Hi @LuisCoelho1971,

How to do to build the SSRS project inside Azure DevOps?
(MSBuild does not work : _rptproj is not supported by MSBuild and cannot be built_)

How to do to generate the ReportingServices.xml file?

Thank you.

**Comment by codehunter13** [comment]
got the same question...

**Comment by codehunter13** [comment]
See https://github.com/mmajcica/DeploySsrs/issues/10
