### ISSUE TITLE
Not sure if errors are from report deployment or the add-in

### ISSUE THREAD

**Issue by acds** [mmajcica/DeploySsrs#39]
Hi @mmajcica 

I'm getting this error:
```
2019-12-13T21:56:02.3378796Z ##[error]Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "'.', hexadecimal value 0x00, is an invalid character. Line 5057, position 10."
```
This seems to be coming from the add-in than a specific report.  

I have a `DeployConfig.json` that is ~450 lines long. it gets to about line 50 before it fails, if I remove the report at the part of the file it then fails on the next etc.
 
Any hints on how to diagnose and resolve appreciated

**Comment by acds** [comment]
Seems it was an issue with he RDL files...but the admin does not say way file these error come from, and aborts after first file with issue, than continue with next until complete - this way you'd know all the file with issues.

Otherwise you have to fix each file in turn and go though. build.deploy cycle, and retry until you have fixed them all.

It would be great as an enhancement if the level or error reporting was improved! 

Apart from that its a great add-in. 

We have the DeployConfig.json file being generating in the build process based on the repo file structure, and added to the build artifact, where this add-in is configured to pick it up for the deploy.

**Comment by mmajcica** [comment]
Judging by the error it seems it has to do with an illegal char in your xml file, seems it can't be parsed.

**Comment by acds** [comment]
I think what I was suggesting was an enhancement that errors indicate what RDL file the process is on, or to add deployment task logging to show where the deploy process the task is.

My current process deploys over 100 RDL files.

There could be a setting in the task to turn verbose logging on?
