### ISSUE TITLE
How to Setup the basic fields on the Deploy Reports agent

### ISSUE THREAD

**Issue by ashishr10** [mmajcica/DeploySsrs#42]
Couple of issues i have run into 
1) Where is the windows authentication user set up ? per your overview, it says in the machine section but i am unable to locate it 
2)Does the SSRS report server URL need to have a publicly exposed URL for the agent to communicate with the server ?

**Comment by mmajcica** [comment]
Your SSRS Server webservice needs to be reachable by the agent.
Windows authentication I suppose if that is the case, calls are made by the build server user identity.
