### ISSUE TITLE
Cannot authenticate against ReportService2010.asmx

### ISSUE THREAD

**Issue by asherman-hsi** [mmajcica/DeploySsrs#49]
Hello,

I have an SSRS server deployed as a VM in Azure and I am trying to use the hosted pipelines from Azure DevOps to deploy reports, but I am unable to successfully retrieve the .asmx file as part of the pipeline.  

##[error]There was an error downloading 'https://[XXX.XXX.XXX.XXX/ReportServer/ReportService2010.asmx'.

I have tried Windows Auth, as well as SQL Auth, using several different username and password options.  It does not appear there is a way to authenticate with the forms-based authentication.  I assume that this is intended to be run from a build agent that is part of the same domain as the SSRS server, but that is not the case for our environment.  I would like to be able to deploy using this pipeline task in this environment.

**Comment by JinrohBI** [comment]
Hello,

You have to use a SelfHosted agent, running with a domain account grant on SSRS Server, and use the Windows Auth in task.

Alex.

**Comment by asherman-hsi** [comment]
Okay, that was basically my conclusion.  Unfortunately that doesn't work for our use case.  Feel free to consider this a feature request, but I understand it's not likely to match the current scope of the project.
