### ISSUE TITLE
 Error: Provided files folder path is not valid

### ISSUE THREAD

**Issue by rp557rajendra** [mmajcica/DeploySsrs#5]
**Issue:**
I am facing issue with Report Files Path. Error is - ##[error]Provided files folder path.

**Overview:**
I am using VSTS with On-premise build agent and OAuthToken has been set.
I have provided Report Files Paths as "**/*.rdl "  assuming it will pick up all the .rdl files in my $(build.sourcesDirectory) path. There are .rdl files in the subfolder of $(build.sourcesDirectory).However, I am still facing the issue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35410163/43646029-b6a5f42c-9701-11e8-8ac5-b7065dd04246.png)

![image](https://user-images.githubusercontent.com/35410163/43646106-f2cd8d7a-9701-11e8-8511-bf65882b6656.png)

![image](https://user-images.githubusercontent.com/35410163/43646168-2523f0d4-9702-11e8-979e-b51d31b3defb.png)

**Comment by mmajcica** [comment]
Hi,

the documentation is a bit of a mess. It is expected from the task to receive a folder where all of the rdl's are located. Something like $(build.sourcesDirectory)\your\rdl\folder

Can you try that and I'll soon update the documentation?

Cheers

**Comment by rp557rajendra** [comment]
Thank you for the quick response.

Based on your feedback and relooking into the issue, it seems Report Files Paths should be **a folder name** where the report exists(ex:$(build.sourcesDirectory)\your\rdl\folder). 

**It is not working if Report Files Paths is provided as below**
1) Complete Report file name(ex: $(build.sourcesDirectory)\your\rdl\folder\myreport.rdl) or 
2) Wild cards ($(build.sourcesDirectory)\your\rdl\folder\**/*.rdl or **/*.rdl) as specified in documentation / VSTS help text message(attached **screenshot**). So , please fix it/change documentation.

**screenshot**
![image](https://user-images.githubusercontent.com/35410163/43651708-1eae9038-9711-11e8-8b1a-1a6b43f148b3.png)

I am able to fix this Report File Path issue by specifying with Report Folder name.  I am facing issues with ReportConfiguration.xml. 

You can close this ticket. Will raise a new ticket, if I find any issues with ReportConfiguration.xml.

**Comment by mmajcica** [comment]
Indeed the docs are misleading. I need to improve on that and somewhere in September, I'll do so.

**Comment by mmajcica** [comment]
Also, SSRS task is quite similar to SSIS task. You may read more about it here http://blog.majcica.com/2018/04/25/deploy-ssis-packages-from-tfs-vsts-build-release/

Hopefully, it will answer your questions regarding the configuration
