### ISSUE TITLE
Exception calling "CreateFolder"

### ISSUE THREAD

**Issue by mywarhistory** [mmajcica/DeploySsrs#54]
Exception calling "CreateFolder" with "3" argument(s): "The permissions granted to user '_Build' are insufficient for performing this operation. ---> Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: The permissions granted to user 'DOT\TFS12PRD_Build' are insufficient for performing this operation."

I have a TFS report structure structure with no folders in it. simple SSRS project inside the Visual Studio solution. 

What is the proper settings in the config file?

I have a report server at /Reports/browse/ENGINEERING/Consultant%20Services

TFS REPO is WebsiteSolution/SSRSReportsProject/report1.rdl

<?xml version="1.0" encoding="utf-8"?>
<Folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" Name="Root">
  <Folders>
    <Folder Name="Folder">
      <Folders>

		  <Folder Name="ENGINEERING/Consultant Services" Hidden="true" CleanExistingItems="false">
			  <Reports>
				  <Report Name="Report1" Hidden="false" FileName="Report1.rdl" />
			  </Reports>
		  </Folder>
			  
      
      </Folders>
      <Security>
        <Security Name="Users">
          <Roles>
            <Role>Browser</Role>
          </Roles>
        </Security>
        <Security Name="Administrator">
          <Roles>
            <Role>Browser</Role>
            <Role>Content Manager</Role>
          </Roles>
        </Security>
      </Security>
    </Folder>
  </Folders>
</Folder>

**Comment by mywarhistory** [comment]
solution to do folders and sub folders. 

<?xml version="1.0" encoding="utf-8"?>
<Folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" Name="Root">
  <Folders>
    <Folder Name="ENGINEERING">
      <Folders>
        <Folder Name="Consultant Services">
					 <Reports>
		    	  <Report Name="Report1" Hidden="false" FileName="Report1.rdl" />
			    </Reports>
        </Folder>
			</Folders>

    </Folder>
  </Folders>
</Folder>

**Comment by alextfreitas** [comment]
I'm having the same exact problem as described above.  What is the solution?

**Comment by mywarhistory** [comment]
> I'm having the same exact problem as described above. What is the solution?

you have to use folder structure that matches SSRS. It was very confusing to me as well.

e.g.

<?xml version="1.0" encoding="utf-8"?>
<Folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" Name="Root">
	<Folders>
		<Folder Name="ENGG">
			<Folders>
				<Folder Name="Consultants">
					<Reports>
						<Report Name="Report99" Hidden="false" FileName="Report99.rdl" />
					</Reports>
				</Folder>
			</Folders>
		</Folder>
	</Folders>
</Folder>
