### ISSUE TITLE
Default value for endpoint not working

### ISSUE THREAD

**Issue by phkrug** [mmajcica/DeploySsrs#59]
https://github.com/mmajcica/DeploySsrs/blob/85944c66a4fd3b8f9fe747ee54209fdf02a110bf/task/task.json#L39
The specified default value will not work in this current setting. As it not ends on .asmx the full URL will look like the following when run:
`http://your.server/ReportServer/ReportService2010.asmx?wsdl/ReportService2010.asmx`

It works without the `?wsdl` though.

**Comment by mmajcica** [comment]
Would you be so kind to make a PR for this and I'll merge it right away?

Thanks
