### ISSUE TITLE
Unable to create subfolders

### ISSUE THREAD

**Issue by rp557rajendra** [mmajcica/DeploySsrs#6]
I have the following XML and expecting to create these folder structures in the report server.
However, it is creating only data source but not the subfolders.

Please help me out by specifying the correct way of specifying the XML to create subfolders and reports in subfolders.

**This is the XML used**
![image](https://user-images.githubusercontent.com/35410163/43726789-15752248-996e-11e8-9356-89189525b809.png)

**Expected FOLDER Structure on Report Server**

_screenshot1 - My ROOT folder structure_
![image](https://user-images.githubusercontent.com/35410163/43726111-3e3cbb98-996c-11e8-9b89-7a0ef06f6423.png)

_screenshot2 - My ENV folder structure_

![image](https://user-images.githubusercontent.com/35410163/43726251-a531d73e-996c-11e8-82f1-c2d3df18032f.png)

_screenshot2 - My Reports structure_
Lets say I have two reports under HOME -->QA-->AREPORTS
![image](https://user-images.githubusercontent.com/35410163/43726273-b8a92c4a-996c-11e8-8da8-3e8fb44c69f1.png)

**Comment by ZacHamilton** [comment]
I see the problem.  The config file needs to have a <Folders> in each folder you intend to have sub-folders.  For example, in the example provided:
  <Folders>
    <Folder Name="Folder">
      <Folders>
        <Folder Name="Datasources" Hidden="true">

The above creates: Folder\DataSources

To fix your config you need to adjust your config file as follows:
...
<Folders>
  <Folder Name="QA">
    <Folders>
      <Folder Name = "AReports">
...

**Comment by rp557rajendra** [comment]
You can close the trick. Based on your suggestion, I have added "FOLDERS" tag and I am able to create subfolders. Added below screenshot so that it might help others

![image](https://user-images.githubusercontent.com/35410163/43751404-bee6016a-99ca-11e8-8b60-2ffd429a2b4d.png)
