### ISSUE TITLE
Deploy error The 'class' keyword is not supported in this version of the language.

### ISSUE THREAD

**Issue by orly665** [mmajcica/DeploySsrs#65]
getting a "class" 

2020-09-29T11:23:14.7232717Z ##[section]Starting: Deploy reports
2020-09-29T11:23:14.7421302Z ==============================================================================
2020-09-29T11:23:14.7421572Z Task         : Deploy MS SQL SSRS Reports
2020-09-29T11:23:14.7421796Z Description  : Deploy items on MS SQL SSRS server based on a configuration file.
2020-09-29T11:23:14.7422013Z Version      : 3.1.10
2020-09-29T11:23:14.7422157Z Author       : Mario Majcica
2020-09-29T11:23:14.7423153Z Help         : 
2020-09-29T11:23:14.7423328Z ==============================================================================
2020-09-29T11:23:15.6801281Z ##[error]At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1157 char:1
+ class Folder
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1199 char:13
+     [string]Path()
+             ~~~~
Unexpected token 'Path' in expression or statement.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1199 char:18
+     [string]Path()
+                  ~
An expression was expected after '('.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1210 char:1
+ class Report
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1235 char:1
+ class DataSet
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1260 char:1
+ class DataSource
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1302 char:1
+ class RoleAssignment
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1313 char:14
+     [string] ToString() { return "$($this.Name)" }
+              ~~~~~~~~
Unexpected token 'ToString' in expression or statement.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1313 char:23
+     [string] ToString() { return "$($this.Name)" }
+                       ~
An expression was expected after '('.

At C:\Azure_agent\_work\_tasks\DeploySsrs_8608c690-a833-11e7-a937-ebb9e5076155\3.1.10\ps_modules\ssrs.psm1:1316 char:1
+ class SsrsDataSource
+ ~~~~~
The 'class' keyword is not supported in this version of the language.

Not all parse errors were reported.  Correct the reported errors and try again.

2020-09-29T11:23:15.7003772Z ##[section]Finishing: Deploy reports

**Comment by mmajcica** [comment]
This looks like you do not have PowerShell 5 installed on your agent machine.

**Comment by orly665** [comment]
Thank you very much, will add Powershell 5 to our Agent m/c
