### ISSUE TITLE
If multiple Shared DataSource exist with the same name at the moment of the deployment, DataSource's reference in shared Datasets can be updated to an invalid one

### ISSUE THREAD

**Issue by GregoryOtt** [mmajcica/DeploySsrs#71]
I Have one staging SSRS server for multiple environments (FAT, UAT, Features, etc.)
SSRS artifacts are deployed on a specifiic folder corresponding to the environment
![image](https://user-images.githubusercontent.com/4428998/113887436-c5538700-97c1-11eb-8d0d-850a5b329683.png)

In each folder the structure is the same and all artifact have the same name.

While deploying, the reference to datasource in the shared datasets are updated according to the first Datasource found with the same name as the reference
https://github.com/mmajcica/DeploySsrs/blob/fea9b6dcedf8b7794f73bc237ad5d63cecf5c228/task/ps_modules/ssrs.psm1#L1123

We should use reference to created Datasources when creating Datasets

**Comment by mmajcica** [comment]
It's been 3 years since I last worked on this. I have nowhere to test any of this. If you are actively working with it and do have a chance to spin this with various situations, feel free to fix what necessary and will be more than happy to assist.

**Comment by GregoryOtt** [comment]
@mmajcica : I've just tested it, it works in my context. 
The #72 is the result of my local test on my company's Azure DevOps Server. My version of the extension is deployed on it. Because it's an Azure DevOps Server, I can package and update the extension myself, no more action from you is required.

I've no other environment/context to test it.

**Comment by hdouglassjr** [comment]
Hi @GregoryOtt , I am in the process of also setting this up with Azure DevOps, can you share your package and configuration you used to get it working on your end?  I was trying to use this extension from @mmajcica , but realized in this post it has not been worked on in a while.  Any help would be appreciated.

**Comment by GregoryOtt** [comment]
Could you please open a new issue with your problem and some details so we can investigate?
