### ISSUE TITLE
How to migrate the same report which was developed with SHARED DATA SOURCE to any other datasources(depending upon env) using XML config

### ISSUE THREAD

**Issue by rp557rajendra** [mmajcica/DeploySsrs#8]
I have various reports in DEV , QA and PROD environemnts .
Each environment has its own DataSource name. For example, DEVDATASOURCE, QADATASOURCE, and PRODDATASOURCE.

My objective is to develop an SSRS report, "Report1" by specifying its data source as DEVDATASOURCE and then use DEPLOY SSRS task to deploy and migrate "REPORT1" from DEV -> QA ->PROD.

Is there any way I can achieve my objective using this DEPLOY SSRS task? If so, could you please explain it.

**Comment by rp557rajendra** [comment]
I did more research on this .

Looks like DEPLOY SSRS build task is not able to modify the DATASOURCE for reports which has been developed with datasource as SHARED DATA SOURCE . If go back to RDL Design for the same report and modify the datasource to EmbededConnection and then do re-deployment then it is working fine . 

Would you please fix the issue for SHARED DATA SOURCE?

Attached are the screenshots.  

![image](https://user-images.githubusercontent.com/35410163/43797751-7113c922-9a56-11e8-9847-a818a0d5f2da.png)

![image](https://user-images.githubusercontent.com/35410163/43798984-2ce23e42-9a5a-11e8-8fdc-be210b6d570f.png)

**Comment by rp557rajendra** [comment]
Any update on this?

**Comment by mmajcica** [comment]
No updates on this. I do understand that this is your way of working and no customization will be made to please you edge case. Artifacts in general should not contain any references about the environment, so use the same name for Datasources, independent from the environments.

**Comment by ZacHamilton** [comment]
I get by with something like so:

``
