### ISSUE TITLE
Help with the configuration file

### ISSUE THREAD

**Issue by ielattar** [mmajcica/DeploySsrs#81]
Hello,
I am trying to user your task but not sure how to use the configuration. I typically just use the report server interface to upload reports to a specific SSRS folder. Is your configuration file based on any standard SSRS built in config file required by the report server end point , http://servername:8080/ReportServer/ReportService2010.asmx ? I am trying to test your task on my end using an agent on my machine. I loaded both the report and your config file on Azure devops git repo. I have not attempted to modify your sample config file yet. Currently I am getting the following error when i run the pipeline.

2022-06-09T15:31:50.3913455Z ##[error]Provided files folder path C:\agent\_work\r2\a\SSRS Source\test.rdl is not valid.

I am sure the path to the report is correct. It was downloaded by my agent. Am I getting this error because I did not modify your config file ? Can you please advise on what needs to be changed or point me to more documentation ?

Thanks in advance

**Comment by AlspachS** [comment]
1.  In the readme, he says, "Considering there is no official way to specify the path where a report should be deployed, a custom configuration file is provided..."

2.  You will have to write a custom config file.  You'll need one for each environment (or a base config file and transform files).  

3.  Don't include the report name in the path to the .rdl files.  Just the folder they're in.

For me, an agent wasn't necessary, just the endpoint.

**Comment by eidun10** [comment]
@AlspachS  are you referring to this?
`<Reports>
						<Report Name="Users report" Hidden="false" FileName="Report_593_Test.rdl" />
					</Reports>`
And which folder are you talking about? Can you give an example please?
